//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPubWS_Cliente.OtroNameSpace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softpub.pucp.edu.pe/", ConfigurationName="OtroNameSpace.ServicioWeb")]
    public interface ServicioWeb {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softpub.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softpub.pucp.edu.pe/ServicioWeb/sumarRequest", ReplyAction="http://services.softpub.pucp.edu.pe/ServicioWeb/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWS_Cliente.OtroNameSpace.sumarResponse sumar(SoftPubWS_Cliente.OtroNameSpace.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softpub.pucp.edu.pe/ServicioWeb/sumarRequest", ReplyAction="http://services.softpub.pucp.edu.pe/ServicioWeb/sumarResponse")]
        System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.sumarResponse> sumarAsync(SoftPubWS_Cliente.OtroNameSpace.sumarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softpub.pucp.edu.pe/ServicioWeb/helloRequest", ReplyAction="http://services.softpub.pucp.edu.pe/ServicioWeb/helloResponse")]
        SoftPubWS_Cliente.OtroNameSpace.helloResponse hello(SoftPubWS_Cliente.OtroNameSpace.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softpub.pucp.edu.pe/ServicioWeb/helloRequest", ReplyAction="http://services.softpub.pucp.edu.pe/ServicioWeb/helloResponse")]
        System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.helloResponse> helloAsync(SoftPubWS_Cliente.OtroNameSpace.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softpub.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softpub.pucp.edu.pe/ServicioWeb/multiplicarRequest", ReplyAction="http://services.softpub.pucp.edu.pe/ServicioWeb/multiplicarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWS_Cliente.OtroNameSpace.multiplicarResponse multiplicar(SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softpub.pucp.edu.pe/ServicioWeb/multiplicarRequest", ReplyAction="http://services.softpub.pucp.edu.pe/ServicioWeb/multiplicarResponse")]
        System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.multiplicarResponse> multiplicarAsync(SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://services.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://services.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://services.softpub.pucp.edu.pe/", Order=0)]
        public SoftPubWS_Cliente.OtroNameSpace.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(SoftPubWS_Cliente.OtroNameSpace.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://services.softpub.pucp.edu.pe/", Order=0)]
        public SoftPubWS_Cliente.OtroNameSpace.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(SoftPubWS_Cliente.OtroNameSpace.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicar", WrapperNamespace="http://services.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class multiplicarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public multiplicarRequest() {
        }
        
        public multiplicarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicarResponse", WrapperNamespace="http://services.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class multiplicarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public multiplicarResponse() {
        }
        
        public multiplicarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebChannel : SoftPubWS_Cliente.OtroNameSpace.ServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebClient : System.ServiceModel.ClientBase<SoftPubWS_Cliente.OtroNameSpace.ServicioWeb>, SoftPubWS_Cliente.OtroNameSpace.ServicioWeb {
        
        public ServicioWebClient() {
        }
        
        public ServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWS_Cliente.OtroNameSpace.sumarResponse SoftPubWS_Cliente.OtroNameSpace.ServicioWeb.sumar(SoftPubWS_Cliente.OtroNameSpace.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int a, int b) {
            SoftPubWS_Cliente.OtroNameSpace.sumarRequest inValue = new SoftPubWS_Cliente.OtroNameSpace.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            SoftPubWS_Cliente.OtroNameSpace.sumarResponse retVal = ((SoftPubWS_Cliente.OtroNameSpace.ServicioWeb)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.sumarResponse> SoftPubWS_Cliente.OtroNameSpace.ServicioWeb.sumarAsync(SoftPubWS_Cliente.OtroNameSpace.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.sumarResponse> sumarAsync(int a, int b) {
            SoftPubWS_Cliente.OtroNameSpace.sumarRequest inValue = new SoftPubWS_Cliente.OtroNameSpace.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((SoftPubWS_Cliente.OtroNameSpace.ServicioWeb)(this)).sumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWS_Cliente.OtroNameSpace.helloResponse SoftPubWS_Cliente.OtroNameSpace.ServicioWeb.hello(SoftPubWS_Cliente.OtroNameSpace.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            SoftPubWS_Cliente.OtroNameSpace.helloRequest inValue = new SoftPubWS_Cliente.OtroNameSpace.helloRequest();
            inValue.Body = new SoftPubWS_Cliente.OtroNameSpace.helloRequestBody();
            inValue.Body.name = name;
            SoftPubWS_Cliente.OtroNameSpace.helloResponse retVal = ((SoftPubWS_Cliente.OtroNameSpace.ServicioWeb)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.helloResponse> SoftPubWS_Cliente.OtroNameSpace.ServicioWeb.helloAsync(SoftPubWS_Cliente.OtroNameSpace.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.helloResponse> helloAsync(string name) {
            SoftPubWS_Cliente.OtroNameSpace.helloRequest inValue = new SoftPubWS_Cliente.OtroNameSpace.helloRequest();
            inValue.Body = new SoftPubWS_Cliente.OtroNameSpace.helloRequestBody();
            inValue.Body.name = name;
            return ((SoftPubWS_Cliente.OtroNameSpace.ServicioWeb)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWS_Cliente.OtroNameSpace.multiplicarResponse SoftPubWS_Cliente.OtroNameSpace.ServicioWeb.multiplicar(SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest request) {
            return base.Channel.multiplicar(request);
        }
        
        public int multiplicar(int a, int b) {
            SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest inValue = new SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest();
            inValue.a = a;
            inValue.b = b;
            SoftPubWS_Cliente.OtroNameSpace.multiplicarResponse retVal = ((SoftPubWS_Cliente.OtroNameSpace.ServicioWeb)(this)).multiplicar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.multiplicarResponse> SoftPubWS_Cliente.OtroNameSpace.ServicioWeb.multiplicarAsync(SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest request) {
            return base.Channel.multiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWS_Cliente.OtroNameSpace.multiplicarResponse> multiplicarAsync(int a, int b) {
            SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest inValue = new SoftPubWS_Cliente.OtroNameSpace.multiplicarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((SoftPubWS_Cliente.OtroNameSpace.ServicioWeb)(this)).multiplicarAsync(inValue);
        }
    }
}
