//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPubBO.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", ConfigurationName="ServicioWeb.ServicioWeb")]
    public interface ServicioWeb {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_modificarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.especialidad_modificarResponse especialidad_modificar(SoftPubBO.ServicioWeb.especialidad_modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_modificarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_modificarResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_modificarResponse> especialidad_modificarAsync(SoftPubBO.ServicioWeb.especialidad_modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_obtenerPorIdRequest" +
            "", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_obtenerPorIdRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.especialidad_obtenerPorIdResponse especialidad_obtenerPorId(SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_obtenerPorIdRequest" +
            "", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_obtenerPorIdRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_obtenerPorIdResponse> especialidad_obtenerPorIdAsync(SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_listarTodosRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.seccion_listarTodosResponse seccion_listarTodos(SoftPubBO.ServicioWeb.seccion_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_listarTodosRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_listarTodosResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_listarTodosResponse> seccion_listarTodosAsync(SoftPubBO.ServicioWeb.seccion_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_obtenerPorIdRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.seccion_obtenerPorIdResponse seccion_obtenerPorId(SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_obtenerPorIdRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_obtenerPorIdResponse> seccion_obtenerPorIdAsync(SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_insertarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.especialidad_insertarResponse especialidad_insertar(SoftPubBO.ServicioWeb.especialidad_insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_insertarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_insertarResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_insertarResponse> especialidad_insertarAsync(SoftPubBO.ServicioWeb.especialidad_insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_listarTodosRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_listarTodosResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.especialidad_listarTodosResponse especialidad_listarTodos(SoftPubBO.ServicioWeb.especialidad_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_listarTodosRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_listarTodosResponse" +
            "")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_listarTodosResponse> especialidad_listarTodosAsync(SoftPubBO.ServicioWeb.especialidad_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_eliminarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.especialidad_eliminarResponse especialidad_eliminar(SoftPubBO.ServicioWeb.especialidad_eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_eliminarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/especialidad_eliminarResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_eliminarResponse> especialidad_eliminarAsync(SoftPubBO.ServicioWeb.especialidad_eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_insertarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.seccion_insertarResponse seccion_insertar(SoftPubBO.ServicioWeb.seccion_insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_insertarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_insertarResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_insertarResponse> seccion_insertarAsync(SoftPubBO.ServicioWeb.seccion_insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_eliminarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.seccion_eliminarResponse seccion_eliminar(SoftPubBO.ServicioWeb.seccion_eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_eliminarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_eliminarResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_eliminarResponse> seccion_eliminarAsync(SoftPubBO.ServicioWeb.seccion_eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_modificarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubBO.ServicioWeb.seccion_modificarResponse seccion_modificar(SoftPubBO.ServicioWeb.seccion_modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_modificarRequest", ReplyAction="http://servicios.softpub.pucp.edu.pe/ServicioWeb/seccion_modificarResponse")]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_modificarResponse> seccion_modificarAsync(SoftPubBO.ServicioWeb.seccion_modificarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/")]
    public enum nivel {
        
        /// <remarks/>
        PREGRADO,
        
        /// <remarks/>
        MAESTRIA,
        
        /// <remarks/>
        DOCTORADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_modificar", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEspecialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_especialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string facultad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubBO.ServicioWeb.nivel nivel;
        
        public especialidad_modificarRequest() {
        }
        
        public especialidad_modificarRequest(int idEspecialidad, string nombre_especialidad, string facultad, SoftPubBO.ServicioWeb.nivel nivel) {
            this.idEspecialidad = idEspecialidad;
            this.nombre_especialidad = nombre_especialidad;
            this.facultad = facultad;
            this.nivel = nivel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_modificarResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public especialidad_modificarResponse() {
        }
        
        public especialidad_modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string especialidad1Field;
        
        private string facultadField;
        
        private int idEspecialidadField;
        
        private bool idEspecialidadFieldSpecified;
        
        private nivel nivelField;
        
        private bool nivelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("especialidad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string especialidad1 {
            get {
                return this.especialidad1Field;
            }
            set {
                this.especialidad1Field = value;
                this.RaisePropertyChanged("especialidad1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEspecialidadSpecified {
            get {
                return this.idEspecialidadFieldSpecified;
            }
            set {
                this.idEspecialidadFieldSpecified = value;
                this.RaisePropertyChanged("idEspecialidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public nivel nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/")]
    public partial class seccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string departamentoField;
        
        private string idSeccionField;
        
        private string seccion1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idSeccion {
            get {
                return this.idSeccionField;
            }
            set {
                this.idSeccionField = value;
                this.RaisePropertyChanged("idSeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string seccion1 {
            get {
                return this.seccion1Field;
            }
            set {
                this.seccion1Field = value;
                this.RaisePropertyChanged("seccion1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_obtenerPorId", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEspecialidad;
        
        public especialidad_obtenerPorIdRequest() {
        }
        
        public especialidad_obtenerPorIdRequest(int idEspecialidad) {
            this.idEspecialidad = idEspecialidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_obtenerPorIdResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubBO.ServicioWeb.especialidad @return;
        
        public especialidad_obtenerPorIdResponse() {
        }
        
        public especialidad_obtenerPorIdResponse(SoftPubBO.ServicioWeb.especialidad @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_listarTodos", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_listarTodosRequest {
        
        public seccion_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_listarTodosResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubBO.ServicioWeb.seccion[] @return;
        
        public seccion_listarTodosResponse() {
        }
        
        public seccion_listarTodosResponse(SoftPubBO.ServicioWeb.seccion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_obtenerPorId", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idSeccion;
        
        public seccion_obtenerPorIdRequest() {
        }
        
        public seccion_obtenerPorIdRequest(string idSeccion) {
            this.idSeccion = idSeccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_obtenerPorIdResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubBO.ServicioWeb.seccion @return;
        
        public seccion_obtenerPorIdResponse() {
        }
        
        public seccion_obtenerPorIdResponse(SoftPubBO.ServicioWeb.seccion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_insertar", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEspecialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_especialidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string facultad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubBO.ServicioWeb.nivel nivel;
        
        public especialidad_insertarRequest() {
        }
        
        public especialidad_insertarRequest(int idEspecialidad, string nombre_especialidad, string facultad, SoftPubBO.ServicioWeb.nivel nivel) {
            this.idEspecialidad = idEspecialidad;
            this.nombre_especialidad = nombre_especialidad;
            this.facultad = facultad;
            this.nivel = nivel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_insertarResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public especialidad_insertarResponse() {
        }
        
        public especialidad_insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_listarTodos", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_listarTodosRequest {
        
        public especialidad_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_listarTodosResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubBO.ServicioWeb.especialidad[] @return;
        
        public especialidad_listarTodosResponse() {
        }
        
        public especialidad_listarTodosResponse(SoftPubBO.ServicioWeb.especialidad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_eliminar", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEspecialidad;
        
        public especialidad_eliminarRequest() {
        }
        
        public especialidad_eliminarRequest(int idEspecialidad) {
            this.idEspecialidad = idEspecialidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="especialidad_eliminarResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class especialidad_eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public especialidad_eliminarResponse() {
        }
        
        public especialidad_eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_insertar", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idSeccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_seccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string departamento;
        
        public seccion_insertarRequest() {
        }
        
        public seccion_insertarRequest(string idSeccion, string nombre_seccion, string departamento) {
            this.idSeccion = idSeccion;
            this.nombre_seccion = nombre_seccion;
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_insertarResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public seccion_insertarResponse() {
        }
        
        public seccion_insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_eliminar", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idSeccion;
        
        public seccion_eliminarRequest() {
        }
        
        public seccion_eliminarRequest(string idSeccion) {
            this.idSeccion = idSeccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_eliminarResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public seccion_eliminarResponse() {
        }
        
        public seccion_eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_modificar", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idSeccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_seccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string departamento;
        
        public seccion_modificarRequest() {
        }
        
        public seccion_modificarRequest(string idSeccion, string nombre_seccion, string departamento) {
            this.idSeccion = idSeccion;
            this.nombre_seccion = nombre_seccion;
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seccion_modificarResponse", WrapperNamespace="http://servicios.softpub.pucp.edu.pe/", IsWrapped=true)]
    public partial class seccion_modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.softpub.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public seccion_modificarResponse() {
        }
        
        public seccion_modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebChannel : SoftPubBO.ServicioWeb.ServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebClient : System.ServiceModel.ClientBase<SoftPubBO.ServicioWeb.ServicioWeb>, SoftPubBO.ServicioWeb.ServicioWeb {
        
        public ServicioWebClient() {
        }
        
        public ServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.especialidad_modificarResponse SoftPubBO.ServicioWeb.ServicioWeb.especialidad_modificar(SoftPubBO.ServicioWeb.especialidad_modificarRequest request) {
            return base.Channel.especialidad_modificar(request);
        }
        
        public int especialidad_modificar(int idEspecialidad, string nombre_especialidad, string facultad, SoftPubBO.ServicioWeb.nivel nivel) {
            SoftPubBO.ServicioWeb.especialidad_modificarRequest inValue = new SoftPubBO.ServicioWeb.especialidad_modificarRequest();
            inValue.idEspecialidad = idEspecialidad;
            inValue.nombre_especialidad = nombre_especialidad;
            inValue.facultad = facultad;
            inValue.nivel = nivel;
            SoftPubBO.ServicioWeb.especialidad_modificarResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_modificarResponse> SoftPubBO.ServicioWeb.ServicioWeb.especialidad_modificarAsync(SoftPubBO.ServicioWeb.especialidad_modificarRequest request) {
            return base.Channel.especialidad_modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_modificarResponse> especialidad_modificarAsync(int idEspecialidad, string nombre_especialidad, string facultad, SoftPubBO.ServicioWeb.nivel nivel) {
            SoftPubBO.ServicioWeb.especialidad_modificarRequest inValue = new SoftPubBO.ServicioWeb.especialidad_modificarRequest();
            inValue.idEspecialidad = idEspecialidad;
            inValue.nombre_especialidad = nombre_especialidad;
            inValue.facultad = facultad;
            inValue.nivel = nivel;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.especialidad_obtenerPorIdResponse SoftPubBO.ServicioWeb.ServicioWeb.especialidad_obtenerPorId(SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest request) {
            return base.Channel.especialidad_obtenerPorId(request);
        }
        
        public SoftPubBO.ServicioWeb.especialidad especialidad_obtenerPorId(int idEspecialidad) {
            SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest inValue = new SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest();
            inValue.idEspecialidad = idEspecialidad;
            SoftPubBO.ServicioWeb.especialidad_obtenerPorIdResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_obtenerPorIdResponse> SoftPubBO.ServicioWeb.ServicioWeb.especialidad_obtenerPorIdAsync(SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest request) {
            return base.Channel.especialidad_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_obtenerPorIdResponse> especialidad_obtenerPorIdAsync(int idEspecialidad) {
            SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest inValue = new SoftPubBO.ServicioWeb.especialidad_obtenerPorIdRequest();
            inValue.idEspecialidad = idEspecialidad;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.seccion_listarTodosResponse SoftPubBO.ServicioWeb.ServicioWeb.seccion_listarTodos(SoftPubBO.ServicioWeb.seccion_listarTodosRequest request) {
            return base.Channel.seccion_listarTodos(request);
        }
        
        public SoftPubBO.ServicioWeb.seccion[] seccion_listarTodos() {
            SoftPubBO.ServicioWeb.seccion_listarTodosRequest inValue = new SoftPubBO.ServicioWeb.seccion_listarTodosRequest();
            SoftPubBO.ServicioWeb.seccion_listarTodosResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_listarTodosResponse> SoftPubBO.ServicioWeb.ServicioWeb.seccion_listarTodosAsync(SoftPubBO.ServicioWeb.seccion_listarTodosRequest request) {
            return base.Channel.seccion_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_listarTodosResponse> seccion_listarTodosAsync() {
            SoftPubBO.ServicioWeb.seccion_listarTodosRequest inValue = new SoftPubBO.ServicioWeb.seccion_listarTodosRequest();
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.seccion_obtenerPorIdResponse SoftPubBO.ServicioWeb.ServicioWeb.seccion_obtenerPorId(SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest request) {
            return base.Channel.seccion_obtenerPorId(request);
        }
        
        public SoftPubBO.ServicioWeb.seccion seccion_obtenerPorId(string idSeccion) {
            SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest inValue = new SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest();
            inValue.idSeccion = idSeccion;
            SoftPubBO.ServicioWeb.seccion_obtenerPorIdResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_obtenerPorIdResponse> SoftPubBO.ServicioWeb.ServicioWeb.seccion_obtenerPorIdAsync(SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest request) {
            return base.Channel.seccion_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_obtenerPorIdResponse> seccion_obtenerPorIdAsync(string idSeccion) {
            SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest inValue = new SoftPubBO.ServicioWeb.seccion_obtenerPorIdRequest();
            inValue.idSeccion = idSeccion;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.especialidad_insertarResponse SoftPubBO.ServicioWeb.ServicioWeb.especialidad_insertar(SoftPubBO.ServicioWeb.especialidad_insertarRequest request) {
            return base.Channel.especialidad_insertar(request);
        }
        
        public int especialidad_insertar(int idEspecialidad, string nombre_especialidad, string facultad, SoftPubBO.ServicioWeb.nivel nivel) {
            SoftPubBO.ServicioWeb.especialidad_insertarRequest inValue = new SoftPubBO.ServicioWeb.especialidad_insertarRequest();
            inValue.idEspecialidad = idEspecialidad;
            inValue.nombre_especialidad = nombre_especialidad;
            inValue.facultad = facultad;
            inValue.nivel = nivel;
            SoftPubBO.ServicioWeb.especialidad_insertarResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_insertarResponse> SoftPubBO.ServicioWeb.ServicioWeb.especialidad_insertarAsync(SoftPubBO.ServicioWeb.especialidad_insertarRequest request) {
            return base.Channel.especialidad_insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_insertarResponse> especialidad_insertarAsync(int idEspecialidad, string nombre_especialidad, string facultad, SoftPubBO.ServicioWeb.nivel nivel) {
            SoftPubBO.ServicioWeb.especialidad_insertarRequest inValue = new SoftPubBO.ServicioWeb.especialidad_insertarRequest();
            inValue.idEspecialidad = idEspecialidad;
            inValue.nombre_especialidad = nombre_especialidad;
            inValue.facultad = facultad;
            inValue.nivel = nivel;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.especialidad_listarTodosResponse SoftPubBO.ServicioWeb.ServicioWeb.especialidad_listarTodos(SoftPubBO.ServicioWeb.especialidad_listarTodosRequest request) {
            return base.Channel.especialidad_listarTodos(request);
        }
        
        public SoftPubBO.ServicioWeb.especialidad[] especialidad_listarTodos() {
            SoftPubBO.ServicioWeb.especialidad_listarTodosRequest inValue = new SoftPubBO.ServicioWeb.especialidad_listarTodosRequest();
            SoftPubBO.ServicioWeb.especialidad_listarTodosResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_listarTodosResponse> SoftPubBO.ServicioWeb.ServicioWeb.especialidad_listarTodosAsync(SoftPubBO.ServicioWeb.especialidad_listarTodosRequest request) {
            return base.Channel.especialidad_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_listarTodosResponse> especialidad_listarTodosAsync() {
            SoftPubBO.ServicioWeb.especialidad_listarTodosRequest inValue = new SoftPubBO.ServicioWeb.especialidad_listarTodosRequest();
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.especialidad_eliminarResponse SoftPubBO.ServicioWeb.ServicioWeb.especialidad_eliminar(SoftPubBO.ServicioWeb.especialidad_eliminarRequest request) {
            return base.Channel.especialidad_eliminar(request);
        }
        
        public int especialidad_eliminar(int idEspecialidad) {
            SoftPubBO.ServicioWeb.especialidad_eliminarRequest inValue = new SoftPubBO.ServicioWeb.especialidad_eliminarRequest();
            inValue.idEspecialidad = idEspecialidad;
            SoftPubBO.ServicioWeb.especialidad_eliminarResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_eliminarResponse> SoftPubBO.ServicioWeb.ServicioWeb.especialidad_eliminarAsync(SoftPubBO.ServicioWeb.especialidad_eliminarRequest request) {
            return base.Channel.especialidad_eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.especialidad_eliminarResponse> especialidad_eliminarAsync(int idEspecialidad) {
            SoftPubBO.ServicioWeb.especialidad_eliminarRequest inValue = new SoftPubBO.ServicioWeb.especialidad_eliminarRequest();
            inValue.idEspecialidad = idEspecialidad;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).especialidad_eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.seccion_insertarResponse SoftPubBO.ServicioWeb.ServicioWeb.seccion_insertar(SoftPubBO.ServicioWeb.seccion_insertarRequest request) {
            return base.Channel.seccion_insertar(request);
        }
        
        public int seccion_insertar(string idSeccion, string nombre_seccion, string departamento) {
            SoftPubBO.ServicioWeb.seccion_insertarRequest inValue = new SoftPubBO.ServicioWeb.seccion_insertarRequest();
            inValue.idSeccion = idSeccion;
            inValue.nombre_seccion = nombre_seccion;
            inValue.departamento = departamento;
            SoftPubBO.ServicioWeb.seccion_insertarResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_insertarResponse> SoftPubBO.ServicioWeb.ServicioWeb.seccion_insertarAsync(SoftPubBO.ServicioWeb.seccion_insertarRequest request) {
            return base.Channel.seccion_insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_insertarResponse> seccion_insertarAsync(string idSeccion, string nombre_seccion, string departamento) {
            SoftPubBO.ServicioWeb.seccion_insertarRequest inValue = new SoftPubBO.ServicioWeb.seccion_insertarRequest();
            inValue.idSeccion = idSeccion;
            inValue.nombre_seccion = nombre_seccion;
            inValue.departamento = departamento;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.seccion_eliminarResponse SoftPubBO.ServicioWeb.ServicioWeb.seccion_eliminar(SoftPubBO.ServicioWeb.seccion_eliminarRequest request) {
            return base.Channel.seccion_eliminar(request);
        }
        
        public int seccion_eliminar(string idSeccion) {
            SoftPubBO.ServicioWeb.seccion_eliminarRequest inValue = new SoftPubBO.ServicioWeb.seccion_eliminarRequest();
            inValue.idSeccion = idSeccion;
            SoftPubBO.ServicioWeb.seccion_eliminarResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_eliminarResponse> SoftPubBO.ServicioWeb.ServicioWeb.seccion_eliminarAsync(SoftPubBO.ServicioWeb.seccion_eliminarRequest request) {
            return base.Channel.seccion_eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_eliminarResponse> seccion_eliminarAsync(string idSeccion) {
            SoftPubBO.ServicioWeb.seccion_eliminarRequest inValue = new SoftPubBO.ServicioWeb.seccion_eliminarRequest();
            inValue.idSeccion = idSeccion;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubBO.ServicioWeb.seccion_modificarResponse SoftPubBO.ServicioWeb.ServicioWeb.seccion_modificar(SoftPubBO.ServicioWeb.seccion_modificarRequest request) {
            return base.Channel.seccion_modificar(request);
        }
        
        public int seccion_modificar(string idSeccion, string nombre_seccion, string departamento) {
            SoftPubBO.ServicioWeb.seccion_modificarRequest inValue = new SoftPubBO.ServicioWeb.seccion_modificarRequest();
            inValue.idSeccion = idSeccion;
            inValue.nombre_seccion = nombre_seccion;
            inValue.departamento = departamento;
            SoftPubBO.ServicioWeb.seccion_modificarResponse retVal = ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_modificarResponse> SoftPubBO.ServicioWeb.ServicioWeb.seccion_modificarAsync(SoftPubBO.ServicioWeb.seccion_modificarRequest request) {
            return base.Channel.seccion_modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubBO.ServicioWeb.seccion_modificarResponse> seccion_modificarAsync(string idSeccion, string nombre_seccion, string departamento) {
            SoftPubBO.ServicioWeb.seccion_modificarRequest inValue = new SoftPubBO.ServicioWeb.seccion_modificarRequest();
            inValue.idSeccion = idSeccion;
            inValue.nombre_seccion = nombre_seccion;
            inValue.departamento = departamento;
            return ((SoftPubBO.ServicioWeb.ServicioWeb)(this)).seccion_modificarAsync(inValue);
        }
    }
}
